project:
  type: book
  output-dir: ../docs/cv

book:
  title: "Curiculum Vitae"
  author: "Samuel Szoniecky"
  date: "04/02/2024"
  chapters:
    - index.qmd
    - cvReferences.qmd

bibliography_main: cvReferencesArt.bib
bibliography_app: cvReferencesBart.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt


