project:
  type: book
  output-dir: ../docs

book:
  title: "Jardin des connaissances : Modélisation des écosystèmes de connaissances pour une écologie de l'information et de la communication"
  author: "Samuel Szoniecky"
  date: "9/14/2023"
  chapters:
    - index.qmd
    - summary.qmd  
    - intro.qmd    
    - part: cartoConnaissances.qmd
      chapters:
        - principesCarto.qmd
        - positionnements.qmd
        - visees.qmd
        - frayages.qmd
        - resultats.qmd
    - part: modeliserConnaissances.qmd
      chapters:
        - etatArtEpistemo.qmd
        - problemesErgo.qmd
    - part: technoIntello.qmd
      chapters:
        - etatArtTI.qmd
        - realisations.qmd
    - part: perspectives.qmd
      chapters:
        - analyserOntoEthique.qmd
        - capterGout.qmd
        - developper.qmd
        - diffuser.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt
